version: '3.7'
services:
  ayapingping-py:
    image: ayapingping-py
    env_file:
      - .env
    ports:
      - "8080:8080"
    build:
      context: .
    restart: always
    network_mode: "host"
